boxboat/dockhand-jenkins

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy

Promotions of `imageTag/` events currently require defining `registryKey`
If only one registry is defined in the configuration, use that registry by default.  If more than one registry is defined, `registryKey` still must be supplied.

Promote imagetag: use default registry if only one is defined

---

src/com/boxboat/jenkins/pipeline/deploy/kubernetes/HelmDeploy.groovy

Add `helm dependency build` to process `requirements.lock` when the chart has sub chart requirements. The expectation is that the `.lock` file will be checked in, which is generated by `helm dependency update`

Add helm dependency build

---

src/com/boxboat/jenkins/library/buildVersions/GitBuildVersions.groovy
src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy

Adds logic to consider `imageTag/<tag>` events in `BoxDeploy.writeImageTags`

Add imagetag event logic to deploy.writeImageTags

---

docs/config/common.md
resources/com/boxboat/jenkins/config.example.yaml
src/com/boxboat/jenkins/library/config/BaseConfig.groovy
src/com/boxboat/jenkins/library/config/CommonConfigBase.groovy
src/com/boxboat/jenkins/library/config/GlobalConfig.groovy
src/com/boxboat/jenkins/library/notify/NotifyConfig.groovy
src/com/boxboat/jenkins/library/notify/NotifyType.groovy
src/com/boxboat/jenkins/pipeline/BoxBase.groovy
test-resources/com/boxboat/jenkins/test/library/config/globalConfig/test.yaml
test/com/boxboat/jenkins/test/library/config/GlobalConfigTest.groovy
test/com/boxboat/jenkins/test/pipeline/PipelineBase.groovy

Currently, repositories can only define `notifySuccessKeys` and `notifyFailureKeys`, and all notification targets must be globally defined
Many repositories may want to define their own notification targets without updating the global `notifyTargetMap`
This PR introduces a new `NotifyConfig` object that repositories can define, allowing for:
- `targetMap` new targets that the repository adds that can be referenced by key
- `successKeys` from `targetMap` or global `notifyTargetMap`
- `successTargets` new targets that the repository adds
- `failureKeys` from `targetMap` or global `notifyTargetMap`
- `failureTargets` new targets that the repository adds
- `infoKeys` from `targetMap` or global `notifyTargetMap`
- `infoTargets` new targets that the repository adds
This is a breaking change, as …

Add notify config object

---

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy

Prerelease tags are incremented when `tag/release` is incremented
This PR emits those events, so that triggers will run against them

Emit prerelease triggers when release is incremented

---

src/com/boxboat/jenkins/pipeline/deploy/kubernetes/HelmDeploy.groovy
test/com/boxboat/jenkins/test/pipeline/deploy/kubernetes/HelmDeployTest.groovy

Adds helm delete to HelmDeploy to allow for custom deployment use cases where the deployment pipeline needs the ability to delete a helm release

Add helm delete to HelmDeploy

---

resources/com/boxboat/jenkins/config.example.yaml
src/com/boxboat/jenkins/library/config/BaseConfig.groovy
src/com/boxboat/jenkins/library/config/DeployConfig.groovy
src/com/boxboat/jenkins/library/environment/BaseEnvironment.groovy
src/com/boxboat/jenkins/library/environment/Environment.groovy
src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy
test-resources/com/boxboat/jenkins/test/library/config/globalConfig/test.yaml
test-resources/com/boxboat/jenkins/test/pipeline/multiDeployment.jenkins
test/com/boxboat/jenkins/test/library/config/GlobalConfigTest.groovy
test/com/boxboat/jenkins/test/pipeline/deploy/MultiDeploymentTest.groovy

Closes #12 
Added the ability to specify `replicaEnvironments` in the `environmentMap` to allow BoxDeploy to expose multiple `Environments` for a deployment

Add the ability to specify replica environment deployments in the environmentMap

---

src/com/boxboat/jenkins/library/SemVer.groovy
src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy

- Fix bug in `BoxPromote` that prevents non-release semver from being incremented when non-release semver == release semver
- Fix bug in `SemVer` where `isPreRelease` is not set after calling `incrementPreRelease()`

BoxPromote and semver bugfix

---

docs/pipelines/box-build.md
docs/pipelines/box-common.md
docs/pipelines/box-deploy.md
docs/pipelines/box-promote.md
src/com/boxboat/jenkins/library/LibraryScript.groovy
src/com/boxboat/jenkins/library/Utils.groovy
src/com/boxboat/jenkins/library/config/Config.groovy
src/com/boxboat/jenkins/library/git/GitAccount.groovy
src/com/boxboat/jenkins/library/git/GitRepo.groovy
src/com/boxboat/jenkins/pipeline/BoxBase.groovy
test-resources/com/boxboat/jenkins/test/pipeline/build.jenkins
test/com/boxboat/jenkins/test/pipeline/PipelineBase.groovy
test/com/boxboat/jenkins/test/pipeline/deploy/kubernetes/KubePodTest.groovy

Currently relative paths are used in `GitRepo` and `LibraryScript` that do not handle changing directories well
This PR adds the `dir` property to `BoxBase`, and changes directory into `dir` after SCM checkout.  It introduces a `Checkout` stage that runs first, and the rest of the stages called in `wrap()` are now executed inside the `dir`

Add `dir` property to change into directory after checkout

---

src/com/boxboat/jenkins/library/Utils.groovy
src/com/boxboat/jenkins/library/config/CommonConfigBase.groovy
src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy
src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy

Upon review of the repository, `Utils.cleanEvent` is not reliably used
It was originally intended to remove slashes from branch names, but this is handled in `GitBuildVersions` by calling `Utils.alphaNumericDashLower` where slashes need to be removed
The best path forward appears to be to remove the spurious uses of `Utils.cleanEvent`

Remove Utils.cleanEvent

---

src/com/boxboat/jenkins/library/git/GitRepo.groovy
src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy

For `dockhand` configurations where git tagging is being utilized check the current semantic version prior to incrementing to see if it is pointing to the same git hash that the promotion pipeline is preparing to assign to the next version
Closes #25

#25 Add image change checking prior to incrementing semver

---

src/com/boxboat/jenkins/library/docker/DTRClean.groovy

Ensure DTRClean honors `retentionDays`

Fix DTR clean

---

docs/config/global.md
resources/com/boxboat/jenkins/config.example.yaml
src/com/boxboat/jenkins/library/Utils.groovy
src/com/boxboat/jenkins/library/config/GlobalConfig.groovy
src/com/boxboat/jenkins/library/docker/Image.groovy
src/com/boxboat/jenkins/library/docker/Registry.groovy
src/com/boxboat/jenkins/library/gcloud/GCloudAccount.groovy
src/com/boxboat/jenkins/library/gcloud/GCloudGKEDeployTarget.groovy
src/com/boxboat/jenkins/library/gcloud/GCloudRegistry.groovy
src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy
src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
test-resources/com/boxboat/jenkins/test/library/config/globalConfig/test.yaml
test/com/boxboat/jenkins/test/library/config/GlobalConfigTest.groovy

Related: #33 
Adds `GCloudAccount` for logging in using service account key file stored as a Jenkins Secret File credential
Adds `GCloudRegistry` for Docker registry
Adds `GCloudGKEDeployTarget` for GKE Deployment
This will require the Google Cloud SDK to be installed on the agent

Google Cloud: add GCloudRegistry and GCloudGKEDeployTarget

---

src/com/boxboat/jenkins/library/buildVersions/GitBuildVersions.groovy
src/com/boxboat/jenkins/library/config/Config.groovy
src/com/boxboat/jenkins/library/docker/DTRClean.groovy
src/com/boxboat/jenkins/library/docker/HarborRegistryClean.groovy
src/com/boxboat/jenkins/library/docker/ImageManifest.groovy
src/com/boxboat/jenkins/library/docker/ImageManifests.groovy
src/com/boxboat/jenkins/library/git/GitRepo.groovy
src/com/boxboat/jenkins/pipeline/BoxBase.groovy
src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy
src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy
src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy

- Fixes #31 
- Writes image repo path to a text file during build time at `build-versions/image-repos/<image-path>.txt`
- Image cleanup scripts look for a repo path corresponding to the image and if they find one, they call `git ls-remote --heads <remote>` on the repository to get branch listing
- If a branch no longer exists, the `commit-<branch>` tag is a candidate for cleanup if it's older than the retention period
As a side effect of accessing `getBuildVersions()` from `ImageManifests`, I moved it to a global in `Config.groovy` along with `GitAccount`.  This should be OK as `GitAccount` pulls all of it's configuration from `Config.global.git` and did not rely on any variables in `BoxBase`

Clean commit-<branch> tags for branches removed from git

---

src/com/boxboat/jenkins/pipeline/deploy/kubernetes/HelmDeploy.groovy
test/com/boxboat/jenkins/test/pipeline/deploy/kubernetes/HelmDeployTest.groovy

Helm 3 has some subtle differences
```
// Install
2: helm install [CHART] [flags]
3: helm install [NAME] [CHART] [flags]
// Upgrade is the same
2: helm upgrade [RELEASE] [CHART] [flags]
3: helm upgrade [RELEASE] [CHART] [flags]
// Delete
2: helm delete [flags] RELEASE_NAME
3: helm uninstall RELEASE_NAME [...] [flags]
```
Namespace is also a global flag in Helm3, as Tiller is no longer around to track which release is installed in which namespace

Update HelmDeploy with Helm 3 support

---

src/com/boxboat/jenkins/library/buildVersions/GitBuildVersions.groovy

Exposes the metadata about the image tag i.e. what event or version - which could then be reference in a helm deployment

Add image_info metadata to write version methods

---

src/com/boxboat/jenkins/library/git/GitAccount.groovy

Adds a default environment variable if not already set when cloning in the method `gitAccount.clone` to disable StrictHostKeyChecking:
```
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
```
Respects `GIT_SSH_COMMAND` if it is already set, as the user may desire some other behavior by default

Disable StrictHostKeyChecking when calling gitAccount.clone

---

docs/config/common.md
docs/config/global.md
resources/com/boxboat/jenkins/config.example.yaml
src/com/boxboat/jenkins/library/buildVersions/GitBuildVersions.groovy
src/com/boxboat/jenkins/library/config/CommonConfigBase.groovy
src/com/boxboat/jenkins/library/config/Config.groovy
src/com/boxboat/jenkins/library/config/GlobalConfig.groovy
src/com/boxboat/jenkins/library/docker/ImageManifests.groovy
src/com/boxboat/jenkins/library/git/GitConfig.groovy
src/com/boxboat/jenkins/library/git/GitRepo.groovy
src/com/boxboat/jenkins/pipeline/BoxBase.groovy
test-resources/com/boxboat/jenkins/test/library/config/globalConfig/test.yaml
test-resources/com/boxboat/jenkins/test/library/config/repoConfig/test.yaml
test/com/boxboat/jenkins/test/library/config/GitConfigTest.groovy
test/com/boxboat/jenkins/test/library/config/GlobalConfigTest.groovy
test/com/boxboat/jenkins/test/library/config/RepoConfigTest.groovy

Add `git.gitAlternateMap` to support alternate Git Configurations
This is useful if somebody has 2 Git services, such as GitHub and GitLab
The primary Git Configuration is always used for `buildVersionsUrl`, `credential`, and `email`
An alternate account can be selected on a per-repo basis by setting `gitAlternateKey`.  Default is just to use the primary
Git paths for alternate configurations will be prefixed with the key. i.e. an alternate `gitlab` with a repository `git@gitlab.com:boxboat/path.git` would be stored as `gitlab:path`
A precondition is to use the same Private Key to connect to both Git services, since a single key is written to `~/.ssh/id_rsa`

Support Alternate Git Configurations

---

src/com/boxboat/jenkins/library/Utils.groovy
src/com/boxboat/jenkins/pipeline/BoxBase.groovy

Hi Folks!
This PR adds a basic input sanitization function for legal git branch characters, especially with the `overrideBranch` parameter field. 
This fixes an issue with copying and pasting text which can sometimes pick up non-printable characters, whitespace, etc, and fail in a confusing manner as a result.

Add cleanBranch util for basic input sanitization

---

src/com/boxboat/jenkins/library/git/GitAccount.groovy
src/com/boxboat/jenkins/library/git/GitRepo.groovy

I think this could also be a problem for PR branches that use the PR-X branch name

Update isBranchTip for pull request branches

---

src/com/boxboat/jenkins/library/SemVer.groovy
src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
test/com/boxboat/jenkins/test/library/SemVerTest.groovy

Fixes regression caused by [#67](https://github.com/boxboat/dockhand/pull/67). Originally we were not respecting the base semver in the jenkins.yaml if it was greater than the current semver. The fix did not take pre-release semvers into account and this caused RCs off of the `baseSemVer` to always restart their incrementing from the `baseSemVer`. 
If we just don't use `baseSemVer` when the previousSemVer was an RC this will cause an issue if we move to a new base without promoting the last RC

Semver check take prereleases into account

---

build.gradle
src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy

Add method to check whether build has been superseded.  Useful to prevent deployment storms when many builds trigger the same deployment

add checkSuperseded to BoxDeploy

---

src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy

closes #92 
`getImageTagsMetadata` can lead to unexpected behavior if a derived class uses the field name `imageTagsMetadata`

Rename getImageTagsMetadata to readImageTagsMetdata

---

gradle/wrapper/gradle-wrapper.properties

Gradle always drops the patch version from version numbers when it is `.0`, tiny PR to update the gradle `distributionUrl` to fix it from PR #96

Update gradle distributionUrl

---

src/com/boxboat/jenkins/library/notify/SlackJenkinsAppNotifyTarget.groovy

The notification format when using the SlackJenkinsAppNotifyTarget class differs from the SlackWebHookNotifyTarget format. This commit aligns the two message formats to be the same and fixes a slight malformatting issue present only in SlackJenkinsAppNotifyTarget which mangles URLs at the end of the message.

Align Slack notifications for Jenkins app and webhook

---

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy

`preparePromotions` was not passing along the `gitTagPrefix` if it was set to the `gitRepo.getCommitsBetween` method

Properly handle gitTagPrefix in preparePromotions method

---

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
test-resources/com/boxboat/jenkins/test/pipeline/promoteRegctl.jenkins
test/com/boxboat/jenkins/test/pipeline/deploy/kubernetes/KubePodTest.groovy
test/com/boxboat/jenkins/test/pipeline/promote/PromoteTest.groovy

If `regctl` is present on the build agent use it to copy/retag rather than a `docker image pull`, `docker image tag` and `docker image push`

Add regctl promotion to accelerate image promotion
