boxboat/dockhand-jenkins

src/com/boxboat/jenkins/pipeline/BoxBase.groovy, src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy, src/com/boxboat/jenkins/pipeline/common/BoxCommon.groovy, src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy, src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
Fixes issue where subclasses set default property values
=> add setPropertiesFromMap method for pipeline constructors

src/com/boxboat/jenkins/pipeline/BoxBase.groovy
- annotate setPropertiesFromMap with @NonCPS
=> Fix Constructor CPS Exception

resources/com/boxboat/jenkins/config.example.yaml, src/com/boxboat/jenkins/library/aws/AwsProfile.groovy, src/com/boxboat/jenkins/library/config/GlobalConfig.groovy, src/com/boxboat/jenkins/pipeline/common/dockcmd/DockcmdGetSecrets.groovy, test-resources/com/boxboat/jenkins/test/library/config/globalConfig/test.yaml, test-resources/com/boxboat/jenkins/test/pipeline/deployment.jenkins, test/com/boxboat/jenkins/test/library/config/GlobalConfigTest.groovy
Closes #14 
Add support for `dockcmd vault get-secrets` and `dockcmd aws get-secrets`.
=> #14 Add dockcmd secrets support

src/com/boxboat/jenkins/library/docker/DTRClean.groovy, src/com/boxboat/jenkins/library/docker/DtrImageManifest.groovy, src/com/boxboat/jenkins/library/docker/HarborImageManifest.groovy, src/com/boxboat/jenkins/library/docker/HarborRegistryClean.groovy, src/com/boxboat/jenkins/library/docker/ImageManifest.groovy, src/com/boxboat/jenkins/library/docker/ImageManifests.groovy, src/com/boxboat/jenkins/pipeline/common/clean/HarborCleanHelper.groovy, test-resources/com/boxboat/jenkins/test/pipeline/cleanHarbor.jenkins, test/com/boxboat/jenkins/test/pipeline/common/clean/HarborCleanTest.groovy
Add HarborRegistryClean to cleanup `dockhand` managed images stored in Harbor
Closes #26
=> #26 Add HarborRegistryClean

src/com/boxboat/jenkins/library/docker/HarborRegistryClean.groovy
=> Fix harbor clean

src/com/boxboat/jenkins/pipeline/BoxBase.groovy, src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy, src/com/boxboat/jenkins/pipeline/deploy/BoxDeploy.groovy, src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
Adds the Event to Image Summary in `BoxBuild`, `BoxPromote`, and `BoxDeploy`
=> Add Event to Image Summary

docs/config/build.md, resources/com/boxboat/jenkins/sharedLibraryScripts/compose-build.sh, resources/com/boxboat/jenkins/sharedLibraryScripts/compose-down.sh, resources/com/boxboat/jenkins/sharedLibraryScripts/compose-up.sh
Multiple `docker-compose` files may be in the same directory.  Allow supplying file in `composeProfileMap`
=> Allow file in composeProfileMap

docs/config/common.md, docs/pipelines/extending.md, src/com/boxboat/jenkins/library/config/CommonConfigBase.groovy, test-resources/com/boxboat/jenkins/test/library/config/repoConfig/test.yaml, test/com/boxboat/jenkins/test/library/config/RepoConfigTest.groovy
=> Allow user config

docs/config/README.md, docs/config/credentials/README.md, docs/config/credentials/vault-credentials.md, docs/config/global.md, resources/com/boxboat/jenkins/config.example.yaml, src/com/boxboat/jenkins/library/Utils.groovy, src/com/boxboat/jenkins/library/credentials/ICredential.groovy, src/com/boxboat/jenkins/library/credentials/vault/VaultBaseCredential.groovy, src/com/boxboat/jenkins/library/credentials/vault/VaultFileCredential.groovy, src/com/boxboat/jenkins/library/credentials/vault/VaultStringCredential.groovy, src/com/boxboat/jenkins/library/credentials/vault/VaultUsernamePasswordCredential.groovy, src/com/boxboat/jenkins/library/deployTarget/IDeployTarget.groovy, src/com/boxboat/jenkins/library/deployTarget/KubernetesDeployTarget.groovy, src/com/boxboat/jenkins/library/docker/DTRClean.groovy, src/com/boxboat/jenkins/library/docker/HarborRegistryClean.groovy, src/com/boxboat/jenkins/library/docker/Registry.groovy, src/com/boxboat/jenkins/library/gcloud/GCloudAccount.groovy, src/com/boxboat/jenkins/library/gcloud/GCloudGKEDeployTarget.groovy, src/com/boxboat/jenkins/library/gcloud/GCloudRegistry.groovy, src/com/boxboat/jenkins/library/git/GitAccount.groovy, src/com/boxboat/jenkins/library/git/GitConfig.groovy, src/com/boxboat/jenkins/library/notify/SlackWebHookNotifyTarget.groovy, src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy, src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy, test-resources/com/boxboat/jenkins/test/library/config/globalConfig/test.yaml, test/com/boxboat/jenkins/test/library/config/GlobalConfigTest.groovy, test/com/boxboat/jenkins/test/pipeline/PipelineBase.groovy
=> Reference Vault credential in config.yaml

src/com/boxboat/jenkins/library/docker/Registry.groovy
=> Bug fix - wrong object passed

src/com/boxboat/jenkins/library/Utils.groovy
=> Prefer absolute paths when making temp files/directories

src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy
=> Allow additional configurable image tags on push

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
=> add non-null check

docs/config/common.md, src/com/boxboat/jenkins/library/config/CommonConfigBase.groovy, src/com/boxboat/jenkins/library/git/GitAccount.groovy, src/com/boxboat/jenkins/library/git/GitRepo.groovy, test-resources/com/boxboat/jenkins/test/library/config/globalConfig/test.yaml, test-resources/com/boxboat/jenkins/test/library/config/repoConfig/test.yaml, test/com/boxboat/jenkins/test/library/config/GlobalConfigTest.groovy, test/com/boxboat/jenkins/test/library/config/RepoConfigTest.groovy
=> Add support for PR branch names

src/com/boxboat/jenkins/library/git/GitAccount.groovy
=> Fix branch naming

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
=> Respect the baseSemVer when promoting

docs/pipelines/box-promote.md, resources/com/boxboat/jenkins/config.example.yaml, src/com/boxboat/jenkins/library/buildVersions/GitBuildVersions.groovy, src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy, test-resources/com/boxboat/jenkins/test/pipeline/promote.jenkins, test-resources/com/boxboat/jenkins/test/pipeline/promoteCustom.jenkins, test-resources/com/boxboat/jenkins/test/pipeline/promoteCustomHigherVersion.jenkins, test-resources/com/boxboat/jenkins/test/pipeline/promoteCustomVersionMismatch.jenkins, test-resources/com/boxboat/jenkins/test/pipeline/promoteFunctions.jenkins, test/com/boxboat/jenkins/test/pipeline/promote/PromoteCustomHigherVersion.groovy, test/com/boxboat/jenkins/test/pipeline/promote/PromoteCustomTest.groovy, test/com/boxboat/jenkins/test/pipeline/promote/PromoteCustomVersionMismatch.groovy, test/com/boxboat/jenkins/test/pipeline/promote/PromoteFunctionsTest.groovy
=> Allow user to set tag to promote to on promotion

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
=> retag releases even if semver is lower

src/com/boxboat/jenkins/pipeline/BoxBase.groovy
Signed-off-by: Caleb Lloyd <caleblloyd@gmail.com>
=> Add option to specify jenkins yaml filename

src/com/boxboat/jenkins/pipeline/build/BoxBuild.groovy
Currently if a couple conditionals fail, the image summary prints `null`
Add better messaging
=> better messages when no images are pushed

src/com/boxboat/jenkins/library/config/CommonConfigBase.groovy
Signed-off-by: Caleb Lloyd <caleblloyd@gmail.com>
=> de-duplicate event registries

src/com/boxboat/jenkins/library/docker/ArtifactoryClean.groovy, src/com/boxboat/jenkins/library/docker/ArtifactoryCleanRegistry.groovy, src/com/boxboat/jenkins/library/docker/ArtifactoryImageManifest.groovy, src/com/boxboat/jenkins/library/docker/ImageManifests.groovy, src/com/boxboat/jenkins/pipeline/common/clean/ArtifactoryCleanHelper.groovy
=> Add artifactory clean

src/com/boxboat/jenkins/library/buildVersions/GitBuildVersionsClean.groovy, src/com/boxboat/jenkins/pipeline/common/clean/GitBuildVersionsCleanHelper.groovy
Cleanup `commit` image versions that no longer exist in remote repository
=> Git Build Versions Clean

src/com/boxboat/jenkins/library/config/CommonConfigBase.groovy
Signed-off-by: Caleb Lloyd <caleblloyd@gmail.com>
=> remove call to unique() in getEventRegistries

src/com/boxboat/jenkins/pipeline/common/dockcmd/DockcmdGetSecrets.groovy
Signed-off-by: Caleb Lloyd <caleblloyd@gmail.com>
=> fix dockcmd files arg

src/com/boxboat/jenkins/library/buildVersions/GitBuildVersions.groovy
=> Process job-triggers with spaces in the directory

src/com/boxboat/jenkins/library/git/GitRepo.groovy
Realized that someone _could_ put double quotes in a commit message which would have busted the json parsing of the git log... This addresses that problem
=> Safer subject and body parsing

build.gradle, gradle-docker.sh, gradle/wrapper/gradle-wrapper.properties, src/com/boxboat/jenkins/library/yaml/GroovyRepresenter.groovy, src/com/boxboat/jenkins/library/yaml/YamlUtils.groovy
YAML processing updates to address breaking changes introduced by the latest SnakeYAML API plugin
https://plugins.jenkins.io/snakeyaml-api/releases/#version_2.2-111.vc6598e30cc65
=> Address breaking changes introduced by snakeyaml 2.2

src/com/boxboat/jenkins/pipeline/promote/BoxPromote.groovy
=> Fix image promotion reftag logic
